

# make file for triadicmemory and dyadicmemory command line tools

all:
	cc -Ofast triadicmemoryCL.c triadicmemory.c -o /usr/local/bin/triadicmemory
	cc -Ofast dyadicmemoryCL.c  triadicmemory.c -o /usr/local/bin/dyadicmemory
	
	
