

# make file for triadicmemory and dyadicmemory command line tools

all:
	cc -Ofast triadicmemoryCL.c 	triadicmemory.c 	-o /usr/local/bin/triadicmemory
	cc -Ofast dyadicmemoryCL.c  	triadicmemory.c 	-o /usr/local/bin/dyadicmemory
	cc -Ofast monadicmemoryCL.c  	triadicmemory.c 	-o /usr/local/bin/monadicmemory
	cc -Ofast temporalmemoryCL.c  	triadicmemory.c 	-o /usr/local/bin/temporalmemory
	cc -Ofast sparseassociativememory.c 			-o /usr/local/bin/sparseassociativememory

	
	
